### PR TITLE
Deprecate CentOS 6 and Debian 7 on Wazuh Manager compilation

### LINKED ISSUE #2154: Start using CentOS 7 to build Wazuh manager packages and deprecate older versions
## Description

As part of https://github.com/wazuh/wazuh/issues/16279, some dependencies need to be updated in order to fix some vulnerabilities from OpenSSL and CURL.

Updating these dependencies require also to update Python cryptography dependency as explained in https://github.com/wazuh/wazuh/issues/16363. However, this version of cryptography does not support older versions than CentOS 7 anymore (https://github.com/wazuh/wazuh/issues/16128#issuecomment-1463862569).

Since all the pipelines used to build RPM manager packages use an image of CentOS 6, it is necessary to update them and start using CentOS 7.

This is probably something that needs to be done also for DEB manager packages.

## Validation

- [ ] Launch Jenkins pipelines to validate that they work as expected.

### PR DESCRIPTION
**Pull request by jnasselle**
|Related issue|
|---|
|Closes #2154|

## Description

This PR aims to deprecate CentOS 6 and Debian 7 on Wazuh Manager compilation, while still using them for Wazuh Agent compilation.

## Tests

- Build the package in any supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [ ] Solaris
  - [ ] AIX
  - [ ] HP-UX
- [ ] Package installation
- [ ] Package upgrade
- [ ] Package downgrade
- [ ] Package remove
- [ ] Package install/remove/install
- [ ] Change added to CHANGELOG.md

- Tests for Linux RPM
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] `%files` section is correctly updated if necessary
- Tests for Linux deb
  - [ ] Build the package for x86_64
  - [ ] Build the package for i386
  - [ ] Build the package for armhf
  - [ ] Build the package for aarch64
  - [ ] Package install/remove/install
  - [ ] Package install/purge/install
  - [ ] Check file permissions after installing the package
- Tests for macOS
  - [ ] Test the package from macOS Sierra to Mojave
- Tests for Solaris
  - [ ] Test the package on Solaris 10
  - [ ] Test the package on Solaris 11
  - [ ] Check file permissions on Solaris 11 template
- Tests for IBM AIX
  - [ ] `%files` section is correctly updated if necessary
  - [ ] Check the changes from IBM AIX 5 to 7

### CODE REVIEW

**Review by DFolchA — CHANGES_REQUESTED** [review]
Docker images for agent and manager should be named differently when built by the generate_package scripts.

**Comment by jotacarma90** [comment]
Hi @jnasselle 

In order to move forward with this PR, I see that Daniel made a request here about differentiating the names of the agent and manager images in the scripts.
Also the branch needs to be updated as it has some conflicts. 

Thanks in advance!!!

**Comment by jnasselle** [comment]
Hi @jotacarma90 ,
As we have discussed, this PR is no longer assigned to me because of @wazuh/qa ownership. Regarding @DFolchA , he also told me that his review was wrong.

**Comment by ncvicchi** [comment]
Since this was our very first experience with several different technologies, we missed some modifications that were required both at the wazuh-packages as well as Jenkings pipelines to allow the PR associated with this issue to work.
[Particularly there were inconsistencies among the prefix used](https://wazuh-team.slack.com/archives/C038AR25C8N/p1691780241483969), which made the tests to failed but we missed to identify it on time.
Being aware of this ([PR fixing it](https://github.com/wazuh/wazuh-jenkins/pull/5268)) and other minor issues we are re-performing the tests and hopefully finishing it soon.

**Review by DFolchA — DISMISSED** [review]
LGTM

**Comment by jnasselle** [comment]
# Update

4.8.0 is not longer the master branch. Re-targeting this PR

**Review by vikman90 — APPROVED** [review]

**Pull request merged**
