### PR TITLE
Renamed macOS Login Item

### PR DESCRIPTION
**Pull request by verdx**
|Related issue|
|---|
|#2199|

## Description

The name of the script used as a Login Item is changed, thus changing the name of the Login Item appearing on `Settings -> General -> Login Items`. The call to `darwin-init.sh` during the installation has been removed, as it only repeats what is done in the `preinstall.sh` script.

## Tests

- [x] Create the package: https://ci.wazuh.info/job/Packages_builder_macos/9828
- [x] Install it on MacOS Ventura

- [x] Check Login Item
image

### CODE REVIEW

**Comment by snaow** [comment]
Hi @verdx,

Please, continue with the testing with the following cases:
- Upgrade from previous versions (screenshots)
- Reboot macOS and check if the service is running (the agent is running and connected after the reboot)
- Uninstall removes successfully all files (no traces)

**Review by snaow — CHANGES_REQUESTED** [review]
Please, continue with the testing with the following cases:

- Upgrade from previous versions (screenshots)
- Reboot macOS and check if the service is running (the agent is running and connected after the reboot)
- Uninstall removes successfully all files (no traces)

**Comment by verdx** [comment]
# Further testing 

The testing asked for in https://github.com/wazuh/wazuh-packages/pull/2207#pullrequestreview-1434474944 has been completed without error.

<details>
  <summary>Installation of 4.4.1</summary>

```
sh-3.2# curl -O https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.1-1.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5501k  100 5501k    0     0   131M      0 --:--:-- --:--:-- --:--:--  149M
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.1-1.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.4.1...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
sh-3.2# /Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.4.1...
wazuh-execd already running...
wazuh-agentd already running...
wazuh-syscheckd already running...
wazuh-logcollector already running...
wazuh-modulesd already running...
Completed.
```
</details>

<details>
  <summary>Upgrade to 4.4.2</summary>

```
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.2-1\(1\).pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
sh-3.2# 
```
</details>

<details>
  <summary>Check the Login Item</summary>

image

</details>

<details>
  <summary>Uninstall according to documentation</summary>

```
sh-3.2# /Library/Ossec/bin/wazuh-control stop
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
Wazuh v4.4.2 Stopped
sh-3.2# /bin/rm -r /Library/Ossec
sh-3.2# /bin/launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist
sh-3.2# /bin/rm -f /Library/LaunchDaemons/com.wazuh.agent.plist
sh-3.2# /bin/rm -rf /Library/StartupItems/WAZUH
sh-3.2# /usr/bin/dscl . -delete "/Users/wazuh"
sh-3.2# /usr/bin/dscl . -delete "/Groups/wazuh"
sh-3.2# /usr/sbin/pkgutil --forget com.wazuh.pkg.wazuh-agent
Forgot package 'com.wazuh.pkg.wazuh-agent' on '/'.
sh-3.2# ls /Library/Ossec
ls: /Library/Ossec: No such file or directory
sh-3.2# ls /Library/StartupItems/
sh-3.2# ls /Library/LaunchDaemons/
com.amazon.aws.ssm.plist				com.amazon.ec2.macos-init.plist
com.amazon.ec2.ena-ethernet.plist			com.amazon.ec2.monitoring.agents.cpuutilization.plist
sh-3.2# find / | grep wazuh
/System/Volumes/Data/Users/ec2-user/wazuh-agent-4.4.2-1(1).pkg
/Users/ec2-user/wazuh-agent-4.4.1-1.pkg
/Users/ec2-user/wazuh-agent-4.4.2-1(1).pkg
sh-3.2# find / | grep ossec
sh-3.2# 
```
</details>

**Review by rauldpm — CHANGES_REQUESTED** [review]
The macOS sources installation should be modified as this script (darwin-init.sh) is still used: https://github.com/search?q=repo%3Awazuh%2Fwazuh%20darwin-init.sh&type=code

The macOS sources installation guide should be reviewed as it is referencing an old `/Library/StartupItems/OSSEC` file
https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html

**Review by snaow — APPROVED** [review]

**Comment by verdx** [comment]
# Update

After this commentary, https://github.com/wazuh/wazuh-packages/pull/2207#pullrequestreview-1436658559, and speaking with @rauldpm and @DFolchA, the approach to this problem has changed, instead of removing the use of `darwin-init.sh` inside https://github.com/wazuh/wazuh-packages, the repetition of code in `preinstall.sh` has been removed, and the service files, created by `darwin-init.sh` are included inside the package. A new PR has been made in https://github.com/wazuh/wazuh to include the name change for the Login Item, https://github.com/wazuh/wazuh/pull/17190.

**Review by rauldpm — APPROVED** [review]

**Review by DFolchA — APPROVED** [review]

**Pull request merged**
